### ISSUE TITLE
Remove upper constraint for JupyterHub (i.e., `<1.5`)

### ISSUE THREAD

**Issue by jbaksta** [conda-forge/cylc-uiserver-feedstock#28]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I have rudimentarily tested a core install of cylc-uiserver from PyPI against jupyterhub 2.2.2 and I don't see any adverse effects, but as I prefer conda packages, the upper constraint on JupyterHub is keeping the environment from being upgraded to JupyterHub 2.x which has some nice RBAC features.

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by oliver-sanders** [comment]
Hello, we recently relaxed this requirement after testing and came to the same conclusion the PyPi metadata has been updated:

https://github.com/cylc/cylc-uiserver/pull/320/files

However, we didn't update the conda-recipe correctly (apologies), we will release a new build with the corrected metadata shortly.
