### ISSUE TITLE
Review dependency on pytest-runner

### ISSUE THREAD

**Issue by kinow** [conda-forge/cylc-uiserver-feedstock#5]
See TODO comment in the recipe: 

https://github.com/conda-forge/cylc-uiserver-feedstock/blob/dd90def6512402138852555ed3f064b905480bf9/recipe/meta.yaml#L24-L26

I have a vague recollection of fixing this in metomi-isodatetime feedstock. And I think I didn't have time to fix here as it was pointed by an external reviewer when we were ready to release our previous alpha version.

Should be easy to fix (first in cylc-uiserver I think, then in this recipe)

**Comment by MetRonnie** [comment]
Removed in 2eb866bb37205681b8b7e55b1ba5226de19eb317
